[2023-04-23T00:00:55.741+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:00:55.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:00:55.744+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:00:55.744+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:00:55.760+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:00:55.759+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:00:55.761+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:00:55.783+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.045 seconds
[2023-04-23T00:01:20.053+0000] {processor.py:153} INFO - Started process (PID=78) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:01:20.056+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:01:20.058+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:20.058+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:01:20.089+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:20.086+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:01:20.091+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:01:20.136+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.090 seconds
[2023-04-23T00:01:50.768+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:01:50.770+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:01:50.772+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:50.771+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:01:50.784+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:01:50.783+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:01:50.785+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:01:50.813+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.053 seconds
[2023-04-23T00:02:20.992+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:02:20.994+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:02:20.996+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:20.996+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:02:21.018+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:21.015+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:02:21.019+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:02:21.050+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.063 seconds
[2023-04-23T00:02:51.374+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:02:51.377+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:02:51.378+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:51.378+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:02:51.391+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:02:51.389+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.model import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:02:51.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:02:51.419+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.057 seconds
[2023-04-23T00:04:50.064+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:04:50.067+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:04:50.069+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:04:50.068+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:04:50.117+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:04:50.115+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:04:50.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:04:50.171+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.124 seconds
[2023-04-23T00:05:20.463+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:05:20.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:05:20.469+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:20.469+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:05:20.507+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:20.503+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:05:20.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:05:20.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.109 seconds
[2023-04-23T00:05:51.242+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:05:51.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:05:51.248+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:51.247+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:05:51.528+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:05:51.526+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:05:51.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:05:51.556+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.325 seconds
[2023-04-23T00:06:21.636+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:06:21.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:06:21.640+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:21.640+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:06:21.653+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:21.651+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:06:21.654+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:06:21.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.052 seconds
[2023-04-23T00:06:52.400+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:06:52.409+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:06:52.413+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:52.413+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:06:52.488+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:06:52.485+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:06:52.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:06:52.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.215 seconds
[2023-04-23T00:07:49.439+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:07:49.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:07:49.452+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:07:49.452+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:07:49.497+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:07:49.487+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:07:49.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:07:49.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.120 seconds
[2023-04-23T00:08:20.202+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:08:20.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:08:20.208+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:08:20.207+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:08:20.228+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:08:20.225+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:08:20.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:08:20.257+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.073 seconds
[2023-04-23T00:09:23.985+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:09:24.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:09:24.004+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:24.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:09:24.022+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:24.015+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:09:24.025+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:09:24.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.109 seconds
[2023-04-23T00:09:54.767+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:09:54.770+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:09:54.772+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:54.772+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:09:54.793+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:09:54.786+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:09:54.797+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:09:54.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.074 seconds
[2023-04-23T00:10:24.985+0000] {processor.py:153} INFO - Started process (PID=138) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:10:24.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:10:24.989+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:24.989+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:10:25.287+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:25.285+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:10:25.287+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:10:25.307+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.329 seconds
[2023-04-23T00:10:55.810+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:10:55.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:10:55.815+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:55.815+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:10:55.833+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:10:55.831+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:10:55.834+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:10:55.877+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.080 seconds
[2023-04-23T00:11:25.915+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:11:25.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:11:25.918+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:25.918+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:11:25.928+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:25.927+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:11:25.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:11:25.950+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.040 seconds
[2023-04-23T00:11:56.626+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:11:56.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:11:56.631+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:56.631+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:11:56.668+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:11:56.664+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:11:56.670+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:11:56.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.097 seconds
[2023-04-23T00:12:27.340+0000] {processor.py:153} INFO - Started process (PID=342) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:12:27.342+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:12:27.344+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:27.344+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:12:27.358+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:27.356+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:12:27.358+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:12:27.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.047 seconds
[2023-04-23T00:12:58.215+0000] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:12:58.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:12:58.218+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:58.218+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:12:58.229+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:12:58.227+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:12:58.229+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:12:58.251+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.042 seconds
[2023-04-23T00:13:28.879+0000] {processor.py:153} INFO - Started process (PID=444) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:13:28.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:13:28.884+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:28.883+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:13:28.895+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:28.894+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:13:28.896+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:13:28.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.043 seconds
[2023-04-23T00:13:59.445+0000] {processor.py:153} INFO - Started process (PID=495) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:13:59.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:13:59.450+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:59.449+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:13:59.465+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:13:59.463+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:13:59.466+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:13:59.496+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.058 seconds
[2023-04-23T00:14:30.141+0000] {processor.py:153} INFO - Started process (PID=546) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:14:30.143+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:14:30.144+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:14:30.144+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:14:30.155+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:14:30.154+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:14:30.156+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:14:30.176+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.041 seconds
[2023-04-23T00:15:50.107+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:15:50.113+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:15:50.119+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:15:50.119+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:15:50.157+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:15:50.154+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:15:50.158+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:15:50.198+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.097 seconds
[2023-04-23T00:16:20.327+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:16:20.332+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:16:20.335+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:20.335+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:16:20.359+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:20.356+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:16:20.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:16:20.395+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.082 seconds
[2023-04-23T00:16:50.677+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:16:50.680+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:16:50.685+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:50.685+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:16:50.991+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:16:50.989+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:16:50.992+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:16:51.020+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.348 seconds
[2023-04-23T00:17:21.368+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:17:21.370+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:17:21.371+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:21.371+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:17:21.397+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:21.395+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:17:21.398+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:17:21.418+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.056 seconds
[2023-04-23T00:17:51.937+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:17:51.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:17:51.947+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:51.947+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:17:51.990+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:17:51.978+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:17:51.991+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:17:52.056+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.131 seconds
[2023-04-23T00:19:13.908+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:19:13.909+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:19:13.910+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:13.910+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:19:13.935+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:13.926+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:19:13.936+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:19:13.967+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.074 seconds
[2023-04-23T00:19:44.034+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:19:44.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:19:44.037+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:44.037+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:19:44.048+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:19:44.046+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:19:44.049+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:19:44.068+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.038 seconds
[2023-04-23T00:21:04.383+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:21:04.385+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:21:04.387+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:21:04.387+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:21:04.411+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:21:04.407+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:21:04.412+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:21:04.449+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.079 seconds
[2023-04-23T00:22:15.859+0000] {processor.py:153} INFO - Started process (PID=35) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:22:15.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:22:15.862+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:15.862+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:22:15.890+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:15.887+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:22:15.891+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:22:15.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.068 seconds
[2023-04-23T00:22:46.661+0000] {processor.py:153} INFO - Started process (PID=86) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:22:46.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:22:46.666+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:46.665+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:22:46.684+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:22:46.683+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:22:46.685+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:22:46.707+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.055 seconds
[2023-04-23T00:24:20.822+0000] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:24:20.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:24:20.837+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:24:20.837+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:24:20.884+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:24:20.877+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 9, in <module>
    from model_as_service.airflow.plugins import ARIMA
ModuleNotFoundError: No module named 'model_as_service'
[2023-04-23T00:24:20.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:24:20.926+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.124 seconds
[2023-04-23T00:25:57.465+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:25:57.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:25:57.469+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:25:57.469+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:25:57.497+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:25:57.494+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 28, in <module>
    python_callable= None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-04-23T00:25:57.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:25:57.536+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.076 seconds
[2023-04-23T00:26:27.864+0000] {processor.py:153} INFO - Started process (PID=89) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:26:27.867+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:26:27.868+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:27.868+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:26:27.896+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:27.891+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 28, in <module>
    python_callable= None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-04-23T00:26:27.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:26:27.938+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.078 seconds
[2023-04-23T00:26:58.479+0000] {processor.py:153} INFO - Started process (PID=140) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:26:58.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:26:58.482+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:58.482+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:26:58.507+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:26:58.503+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 28, in <module>
    python_callable= None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-04-23T00:26:58.509+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:26:58.543+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.070 seconds
[2023-04-23T00:27:29.169+0000] {processor.py:153} INFO - Started process (PID=191) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:27:29.171+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:27:29.174+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:27:29.174+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:27:29.215+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:27:29.208+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 28, in <module>
    python_callable= None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-04-23T00:27:29.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:27:29.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.098 seconds
[2023-04-23T00:28:00.325+0000] {processor.py:153} INFO - Started process (PID=242) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:28:00.328+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:28:00.331+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:00.330+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:28:00.373+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:00.364+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 28, in <module>
    python_callable= None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-04-23T00:28:00.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:28:00.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.120 seconds
[2023-04-23T00:28:31.607+0000] {processor.py:153} INFO - Started process (PID=293) to work on /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:28:31.614+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/models_dags copy.py for tasks to queue
[2023-04-23T00:28:31.629+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:31.629+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:28:31.662+0000] {logging_mixin.py:137} INFO - [2023-04-23T00:28:31.659+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/models_dags copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/models_dags copy.py", line 28, in <module>
    python_callable= None
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 394, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-04-23T00:28:31.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/models_dags copy.py
[2023-04-23T00:28:31.716+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/models_dags copy.py took 0.118 seconds
